set nocompatible

filetype plugin indent on
syntax on

set noerrorbells
set novisualbell
set number

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smarttab
set shiftround
set autoindent
set smartindent

set nobackup
set nowritebackup
set noswapfile

set hidden
