set nocompatible

filetype plugin indent on
syntax on

set noerrorbells
set novisualbell

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
set shiftround
set autoindent
set smartindent

set nobackup
set nowritebackup
set noswapfile
